SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_INS AS AI JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID=AO.ANIMAL_ID AND AI.ANIMAL_TYPE=AO.ANIMAL_TYPE
WHERE AI.SEX_UPON_INTAKE <> AO.SEX_UPON_OUTCOME;