SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS);

SELECT AO.ANIMAL_ID , AO.NAME
FROM ANIMAL_OUTS AS AO LEFT JOIN ANIMAL_INS AS AI ON (AI.ANIMAL_ID = AO.ANIMAL_ID AND AI.ANIMAL_TYPE = AO.ANIMAL_TYPE) 
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID